import './js/createFilmsGallery';
// import './js/adFilms';
import './js/pagination';
import './js/modal';
import './js/modal-team';
import './js/toTop';
import './js/firebase';
import './js/login-modal';
import './js/signup-modal';
// import './js/login-modal';
